#-----------------------------------------------

title:
  en: "Portal"
  gr: "Δικτυακή Πύλη"
subtitle:
  gr: "All tools in one place"

#-----------------------------------------------

sync: false
contact: false
search: false
cookies: false
footerHidden: true
languages_toolbar: false
languages_sidebar: false
services: true
lockSidebar: false

#-----------------------------------------------

account:
  menu:
    - account

menu:
  image: false
  icon: "icons/agneta/logo"
  title: true

#-----------------------------------------------

recaptcha_key: ""
gmaps_key: ""
disqus_shortname: ""
google_analytics: ""
google_maps: ""

#-----------------------------------------------

authorization:
  - administrator

minify:
  html: true
  js: false

#-----------------------------------------------

scripts:
  app:
    - app
